services:
  localdb:
    image: postgres:16.2
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
