"""models_for_search

Revision ID: 19da2bc01207
Revises: c45f0eff8cca
Create Date: 2024-10-22 14:20:42.432128

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "19da2bc01207"
down_revision: Union[str, None] = "c45f0eff8cca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("articles", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("articles", sa.Column("preview", sa.String(), nullable=False))
    op.add_column("articles", sa.Column("tags", sa.String(), nullable=True))
    op.add_column("articles", sa.Column("user_id", sa.UUID(), nullable=False))
    op.add_column(
        "articles", sa.Column("current_version_id", sa.UUID(), nullable=False)
    )
    op.alter_column(
        "articles",
        "section",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.create_foreign_key(None, "articles", "versions", ["current_version_id"], ["id"])
    op.create_foreign_key(None, "articles", "users", ["user_id"], ["id"])
    op.drop_column("articles", "content")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "articles", sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "articles", type_="foreignkey")
    op.drop_constraint(None, "articles", type_="foreignkey")
    op.alter_column(
        "articles",
        "section",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_column("articles", "current_version_id")
    op.drop_column("articles", "user_id")
    op.drop_column("articles", "tags")
    op.drop_column("articles", "preview")
    op.drop_column("articles", "created_at")
    op.drop_table("versions")
    # ### end Alembic commands ###
