"""user_profile

Revision ID: 48306723aa33
Revises: c442f46fa298
Create Date: 2024-12-01 16:23:09.370599

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "48306723aa33"
down_revision: Union[str, None] = "c442f46fa298"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("profession", sa.String(), nullable=False))
    op.add_column("users", sa.Column("bio", sa.String(), nullable=False))
    op.add_column("users", sa.Column("profile_picture", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "profile_picture")
    op.drop_column("users", "bio")
    op.drop_column("users", "profession")
    # ### end Alembic commands ###
