"""update_enums

Revision ID: c442f46fa298
Revises: 3e1c63916599
Create Date: 2024-10-23 19:37:42.144624

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# ### MANUALLY IMPORTED ###
from app.models import SectionName

# ### MANUALLY CREATE ENUM ###
section_name_enum = sa.Enum(SectionName)


# revision identifiers, used by Alembic.
revision: str = "c442f46fa298"
down_revision: Union[str, None] = "3e1c63916599"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### MANUALLY CREATE ENUM TYPE ###
    section_name_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sections",
        "name",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum(
            "PATOGENO",
            "TRANSMISSOR",
            "PREVENCAO",
            "DADOS",
            "TRATAMENTO",
            name="sectionname",
        ),
        postgresql_using="name::SectionName",
        existing_nullable=False,
    )
    op.alter_column(
        "versions",
        "section",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum(
            "PATOGENO",
            "TRANSMISSOR",
            "PREVENCAO",
            "DADOS",
            "TRATAMENTO",
            name="sectionname",
        ),
        postgresql_using="section::SectionName",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "versions",
        "section",
        existing_type=sa.Enum(
            "PATOGENO",
            "TRANSMISSOR",
            "PREVENCAO",
            "DADOS",
            "TRATAMENTO",
            name="sectionname",
        ),
        type_=sa.VARCHAR(),
        postgresql_using="section::varchar",
        existing_nullable=True,
    )
    op.alter_column(
        "sections",
        "name",
        existing_type=sa.Enum(
            "PATOGENO",
            "TRANSMISSOR",
            "PREVENCAO",
            "DADOS",
            "TRATAMENTO",
            name="sectionname",
        ),
        type_=sa.VARCHAR(),
        postgresql_using="name::varchar",
        existing_nullable=False,
    )
    # ### end Alembic commands ###

    # ### MANUALLY DROP ENUM TYPE ###
    section_name_enum.drop(op.get_bind())
