"""add_sign_up_motivation_and_role

Revision ID: c45f0eff8cca
Revises: b0e8d3e2d09d
Create Date: 2024-10-11 11:01:20.462197

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# ### MANUALLY IMPORTED ###
from app.models import UserRole


# revision identifiers, used by Alembic.
revision: str = "c45f0eff8cca"
down_revision: Union[str, None] = "b0e8d3e2d09d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# ### MANUALLY CREATE ENUM ###
user_role_enum = sa.Enum(UserRole)


def upgrade() -> None:
    # ### MANUALLY CREATE ENUM TYPE ###
    user_role_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("motivation", sa.Text(), nullable=False))
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(),
        type_=user_role_enum,
        postgresql_using="role::UserRole",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "role",
        existing_type=user_role_enum,
        type_=sa.VARCHAR(),
        postgresql_using="role::varchar",
        nullable=True,
    )
    op.drop_column("users", "motivation")
    # ### end Alembic commands ###

    # ### MANUALLY DROP ENUM TYPE ###
    user_role_enum.drop(op.get_bind())
