"""versions

Revision ID: f2a13f7b0db1
Revises: 3b4dfad17c14
Create Date: 2024-10-08 16:37:09.408805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2a13f7b0db1'
down_revision: Union[str, None] = '3b4dfad17c14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('articles', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('articles', sa.Column('preview', sa.String(), nullable=False))
    op.add_column('articles', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('articles', sa.Column('current_version_id', sa.UUID(), nullable=False))
    op.alter_column('articles', 'section',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'articles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'articles', 'versions', ['current_version_id'], ['id'])
    op.drop_column('articles', 'content')
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    op.add_column('articles', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.alter_column('articles', 'section',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('articles', 'current_version_id')
    op.drop_column('articles', 'user_id')
    op.drop_column('articles', 'tags')
    op.drop_column('articles', 'preview')
    op.drop_column('articles', 'created_at')
    op.drop_table('versions')
    # ### end Alembic commands ###
